### ISSUE TITLE
Markdown support for About Me section

### ISSUE THREAD

**Issue by kaustavsarkar** [kaustavsarkar/giveback-schedule#4]
We need to introduce markdown support for About Me section. The reason being, this is the section where folks can express themselves.

**Comment by ShankhadeepBanerjee** [comment]
We can use this npm package: [React-markdown](https://www.npmjs.com/package/react-markdown) 


See this blog: https://blog.logrocket.com/how-to-safely-render-markdown-using-react-markdown/

**Comment by kaustavsarkar** [comment]
Thanks, @ShankhadeepBanerjee for the suggestion. :) it was pretty easy to do.
